### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by GerhardMes** [unshift/airtable-react#2]
I have several error calls in the console. I think, I have modified .env correctly; but the console brings out this error:

GET: https://api.airtable.com/v0/undefined/undefined?maxRecords=undefined&view=undefined 404 not found.

Maybe it's because I get an earlier error in env.js (env2 was required ... invalid json .. followed by a lot 

Any suggestions? I just want to make a simple app listing one table from airtable with several filters.

**Comment by unshift** [comment]
@GerhardMes @kelvinwebdesigner This is resolved.
