### ISSUE TITLE
ReadMe instructions out of date 

### ISSUE THREAD

**Issue by supercgeek** [unshift/airtable-react#3]
Where do I find the Table ID for .env in the Airtable API reference or can I use a plaintext table name?

**Comment by michaelprflores** [comment]
Hi @supercgeek. I was looking for the same thing but it is literally the name of the table. Hope this helps. I have the values in my .env wrapped in quotes too.
![screen shot 2018-11-16 at 11 07 25 am](https://user-images.githubusercontent.com/8737117/48632819-e2d4eb80-e98f-11e8-9cf0-ef0ab5e85d8b.png)

**Comment by unshift** [comment]
@artfuldevelopment is correct. If you visit https://airtable.com/api, login, and click on the table and start flipping through the Airtable API docs, you will see references to your specific table name in the docs.
